sudo: false

os:
  - linux

language: d

d:
  - ldc
  - dmd

env:
  matrix:
    - PY_VER=3.5
    - PY_VER=3.6
    - PY_VER=3.7

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python="${PY_VER}" numpy
  - source activate test-environment

script:
  - make test
